---
# vars file for lamp
packages:
-  epel-release
-  python-pip
-  pexpect
-  httpd
-  http://repo.mysql.com/mysql-community-release-el7-5.noarch.rpm
-  http://rpms.remirepo.net/enterprise/remi-release-7.rpm
-  mysql-server
-  php72
-  php72-php-fpm 
-  php72-php-mysqlnd
-  php72-php-opcache
-  php72-php-xml 
-  php72-php-xmlrpc 
-  php72-php-gd
-  php72-php-mbstring
-  php72-php-json
firewall_whitelist:
- http
- https
- mysql

ports:
- 3306
- 80
- 443

necc_files:
- index.html
- info.php

http_path: /var/www/html/
