---
# vars file for lamp
packages:
-  epel-release
-  python-pip
-  pexpect
-  httpd
-  http://repo.mysql.com/mysql-community-release-el7-5.noarch.rpm
-  php
-  php-mysql
-  php-pdo 
-  php-gd 
-  php-mbstring

firewall_whitelist:
- http
- https
- mysql

ports:
- 3306
- 80
- 443

necc_files:
- index.html
- info.php

http_path: /var/www/html/
