---
- name: upgrade all packages
  yum:
    name: '*'
    state: latest

- name: Install the necessary sofwares for lamp
  package:
    name: "{{ item }}"
    state: installed
  with_items:
  - "{{ packages }}"
  notify: start services

- name: Upgrade pexpect
  pip:
    name: pexpect>3

- name: Copy the default index file
  copy: 
    src:  "{{ item }}"
    dest: "{{ http_path }}" 
  with_items:
  - "{{ necc_files }}"

- name: Autogenerate password for mysql
  shell: "date +%s | sha256sum | base64 | head -c 32 ; echo"
  register: pass
  no_log: true

- set_fact: 
    server_passwd: "{{ pass.stdout }}"
  no_log: true

- name: Create .my.cnf
  file: 
    path: "{{ item }}" 
    state: touch
  with_items:
  - '/root/.my.cnf'
  ignore_errors: yes

- service: name=mysqld state=started enabled=yes

- name: Configure MySQL
  expect:
    command: "mysql_secure_installation"
    responses:
     (?i)current: ""
     (?i)set: "y"
     (?i)new: "{{ server_passwd }}"
     (?i)re-enter: "{{ server_passwd }}"
     (?i)anonymous: "y"
     (?i)remotely: "n"
     (?i)test: "y"
     (?i)tables: "y"
  ignore_errors: yes

- command: systemctl status firewalld
  register: firewall
  ignore_errors: yes

- name: Open the services in Firewall
  firewalld:
    service: "{{ item }}"
    permanent: yes
    state: enabled
  with_items:
  - "{{ firewall_whitelist }}"
  ignore_errors: yes
  when: firewall is success

- name: Open the ports in Firewall.
  firewalld:
    port: "{{ item }}/tcp"
    permanent: yes
    state: enabled
  with_items:
  - "{{ ports }}"
  ignore_errors: yes
  when: firewall is success

- name: Creating the .my.cnf
  blockinfile:
    path: /root/.my.cnf
    block: |
       [client]
       user=root 
       password="{{ server_passwd }}" 
       
- name: Convert php72 to php 
  file: 
    src: /usr/bin/php72
    dest: /usr/bin/php
    state: link
